apiVersion: v1
kind: Pod
metadata:
  name: test-registry-pod
  namespace: default
spec:
  nodeName: k3d-k3s-default-agent-1
  containers:
  - name: test-container
    image: kubelab:5000/ssh-ubuntu:24
    ports:
    - containerPort: 8888
  restartPolicy: Never

